export const formulaIndex = [
  { key: 'clarke', name: 'Clarke 变换', expression: 'Iα = Ia, Iβ = (Ia + 2Ib) / √3' },
  { key: 'park', name: 'Park 变换', expression: 'Id = Iα cosθ + Iβ sinθ, Iq = -Iα sinθ + Iβ cosθ' },
  { key: 'torque', name: 'PMSM 转矩', expression: 'Te = 1.5 p [ψf Iq + (Ld - Lq) Id Iq]' },
  { key: 'svpwm', name: 'SVPWM 调制比', expression: 'm = √3 |Uref| / Udc' },
  { key: 'voltage-limit', name: '电压极限', expression: '√(Vd² + Vq²) ≤ Udc / √3' },
  { key: 'electrical-freq', name: '电频率', expression: 'fe = (rpm / 60) × polePairs' },
  { key: 'bemf', name: '反电动势', expression: 'BEMF = Ke × ω_e × polePairs = ψf × ω_e' },
  { key: 'pi-bandwidth', name: '电流环带宽整定', expression: 'Kp = ω_bw × L,  Ki = ω_bw × R  (零极点对消)' },
  { key: 'antiwindup-bc', name: '抗积分饱和 (Back-Calc)', expression: 'I_term += Kt × (u_sat - u_unsat) × Ts,  Kt ≈ Ki / Kp' },
  { key: 'deadtime-loss', name: '死区电压损失', expression: 'ΔV_dt = (t_dead / Ts) × Udc × sign(I_phase)' },
  { key: 'ocp-i2t', name: 'I²t 过流积分', expression: 'I²t = ∫ I² dt  (累积到阈值即报 FAULT_OC_I2T)' },
  { key: 'vf-ratio', name: 'V/f 启动比例', expression: 'V_cmd = V_min + (V_rated - V_min) × (fe / fe_rated)' },
  { key: 'ramp-rate', name: '反液击斜坡', expression: 'dω/dt ≤ rampRpmS;  压缩机典型 300~800 rpm/s' },
  { key: 'clarke-q15', name: 'Clarke q15 整数实现', expression: 'Iβ = (Ia + 2·Ib) × 18919 >> 15  (18919 ≈ 32768/√3)' },
  { key: 'kcl-residual', name: 'KCL 残差自检', expression: '|I0| = |Ia + Ib + Ic|/3;  健康 < 1% Imax，> 5% 触发偏置/缺相告警' },
  { key: 'dq-decoupling', name: 'dq 解耦前馈', expression: 'vd_ff = −ω·Lq·iq;  vq_ff = ω·(Ld·id + ψf)  (高速段必加)' },
  { key: 'svpwm-minmax', name: 'SVPWM min-max 零序注入', expression: 'voff = −(vmax + vmin)/2;  duty = 0.5 + (v + voff)/Udc' },
  { key: 'hfi-gain', name: 'HFI 凸极信号增益', expression: 'gain = (r − 1)/(r + 1),  r = Lq/Ld;  r=1.5 → 0.20, r=2.5 → 0.43' },
  { key: 'hfi-demod', name: 'HFI 解调误差', expression: 'i_response × cos(ωh·t) → LPF → ≈ 0.5·sin(2·Δθ)' },
  { key: 'pfc-boost', name: 'Boost PFC 升压关系', expression: 'Udc = Vrect / (1 − D);  D=0.4 + 220V AC → Udc ≈ 520V (工程限 D≤0.5)' },
  { key: 'pfc-cap-ripple', name: 'PFC 母线电容纹波', expression: 'ΔUdc ≈ I_load / (2·ω_line·C);  按目标纹波 % 反推 C' },
  { key: 'foc-total-delay', name: 'FOC 总采样-生效延迟', expression: 't_delay ≈ 1.5·Ts (ADC 中点 + CCR 预装载);  电流环带宽上限 ≈ 1/(2π·1.5·Ts)' },
  { key: 'fw-base-speed', name: '弱磁基速', expression: 'ω_base = V_max / ψf;  V_max = Udc/√3 (SVPWM 线性区)' },
  { key: 'fw-id-feedforward', name: '弱磁 Id 前馈解析', expression: 'Id* = √(V_max² − (ωe·Lq·Iq)²) / (ωe·Ld) − ψf/Ld' },
  { key: 'mtpa-ipm', name: 'IPM MTPA 解析解', expression: 'Id* = (ψf − √(ψf² + 8(Ld−Lq)²·Iq²)) / (4(Ld−Lq))' },
  { key: 'voltage-ellipse', name: '电压椭圆', expression: '(ψf + Ld·Id)² + (Lq·Iq)² ≤ (V_max/ωe)²;  中心 (−ψf/Ld, 0)' },
  { key: 'cop', name: '制冷 COP', expression: 'COP = q_c / w = (h₁ − h₄) / (h₂ − h₁)' },
  { key: 'superheat', name: '吸气过热度 SH', expression: 'SH = T_suct − T_sat(P_s);  EEV PI 反馈量，目标 5–10K' },
  { key: 'subcool', name: '冷凝过冷度 SC', expression: 'SC = T_sat(P_d) − T_liquid;  目标 3–7K，<2K 节流闪发气泡' },
  { key: 'comp-torque-from-cycle', name: '压缩机负载转矩', expression: 'τ_load = W_comp / ω_m = (m_dot·w) / (2π·rpm/60)' },
];
