export const glossary = [
  { term: 'FOC', definition: 'Field Oriented Control，磁场定向控制，把电流分解为励磁 Id 和转矩 Iq。' },
  { term: 'SVPWM', definition: 'Space Vector PWM，用空间电压矢量合成三相逆变器占空比。' },
  { term: '电角度', definition: '电磁场周期对应的角度，等于机械角度乘以极对数。' },
  { term: 'Id', definition: 'd 轴电流，通常对应磁链方向；弱磁时常为负。' },
  { term: 'Iq', definition: 'q 轴电流，主要产生电磁转矩。' },
  { term: 'PLL', definition: '锁相环，用相位误差估算并平滑角度/速度。' },
  { term: 'JSQR', definition: 'STM32 ADC 注入通道序列寄存器；JEXTSEL 选 TIM1 TRGO/CC4 作为触发源，让 ADC 在 PWM 中点自动采样。' },
  { term: 'BDTR', definition: 'STM32 高级定时器（TIM1/TIM8）的死区与刹车寄存器；DTG 字段编码死区时间，MOE 是主输出使能。' },
  { term: 'OCP', definition: 'Over-Current Protection 过流保护；硬件比较器 (COMP+TIM1 BKIN) 触发为快速 OCP，软件累积 I²t 触发为慢速 OCP。' },
  { term: 'I²t', definition: '电流平方对时间积分，用来等价模拟绕组温升；超过预设阈值即报"长时过流"，区别于瞬时过流。' },
  { term: 'Z 信号', definition: '增量编码器每圈一次的索引脉冲，用来周期性复位累计计数器漂移；接 TIM 输入捕获中断。' },
  { term: 'CCR', definition: 'Capture / Compare Register；写入 TIMx->CCR1/2/3 决定三相 PWM 占空比，预装载使能后下一周期生效。' },
  { term: '反液击', definition: '压缩机启动时限制加速斜坡（典型 300~800 rpm/s），让液态制冷剂有时间气化避免阀片碎裂。' },
  { term: 'APF', definition: 'Annual Performance Factor 全年能效比，按 GB 21455 加权多工况点；变频机靠部分负荷高 COP 拉高 APF。' },
  { term: 'V/f', definition: '电压频率比开环拖动；启动初段 BEMF 太小观测不到时使用，按 V_min + k·f 给定电压矢量"硬拖"转子。' },
  { term: '抗积分饱和', definition: 'Anti-Windup；PI 输出撞限时停止 / 反算 (Back-Calc) 积分累加，避免 windup 大超调。' },
];
