import type { ModuleWalkthrough } from './types';

/**
 * 04 Park 变换 —— 让"αβ 交流量在 dq 上变直流量"这件事真正可见。
 *
 * 教学路径：先建立旋转坐标几何直觉 → 在 θ=0 / θ=90° 两个静态截面验证矩阵 →
 * 让 θ 跟住转子看直流量浮现 → 体感 Δθ 串扰 → 走通 STM32 上的 sin/cos 查表 +
 * 定点实现 + 编码器 Z 信号对齐 + 高速 dq 交叉解耦五个工业落地坑。
 *
 * 工业绑定：空调/冰箱 PMSM 压缩机，5-8 极对、24-310 V 母线、PWM 8-16 kHz、
 * 用 Cortex-M3 Q15 实现 ISR 内 Park 是国内主流方案；M4F/FPU 才有奢侈用浮点。
 */
export const parkTransformWalkthrough: ModuleWalkthrough = {
  moduleId: 'park-transform',
  bigPicture: '跳到转子上看 αβ → AC 变 DC：给 PI 创造工作前提的旋转变换，所有 dq 串扰、过零抖、低分编码器异响都在这里发生。',
  bigPictureEn: 'Jump onto the rotor frame to view αβ → AC becomes DC: the rotating transform that creates the working precondition for PI; all dq crosstalk, zero-crossing jitter, and low-resolution encoder noises originate here.',
  successCriteria: [
    '能口算 Id = Iα·cosθ + Iβ·sinθ、Iq = −Iα·sinθ + Iβ·cosθ 两条公式，并说明矩阵对应"αβ 顺时针旋转 −θ"',
    '能解释 d 轴沿永磁体 N 极、q 轴领先 90°，为什么 Iq 才是"转矩电流"且 Id=0 时铜损最低',
    '理解 θ 必须是电角度且与转子磁链方向对齐，Δθ 错 15° 会让纯 Iq 命令漏 26% 到 Id',
    '能在 STM32 Q15 实现里避开 sin/cos 表插值、_smmla 累加、防溢出三个坑',
    '能说出为什么压缩机 6000 rpm+ 必须叠加 dq 交叉解耦前馈 (ω·Lq·iq、ω·Ld·id+ω·ψf)',
  ],
  successCriteriaEn: [
    'Mentally apply Id = Iα·cosθ + Iβ·sinθ and Iq = −Iα·sinθ + Iβ·cosθ, and explain the matrix as "rotate αβ by −θ".',
    'Explain that the d axis points along the rotor N pole, q leads by 90°, why Iq is the "torque current", and why Id = 0 minimizes copper loss.',
    'Understand that θ must be the electrical angle aligned with the rotor flux direction, and that a 15° Δθ leaks 26% of a pure Iq command into Id.',
    'Avoid three pitfalls in a Q15 STM32 implementation: sin/cos table interpolation, _smmla accumulation, overflow protection.',
    'State why a compressor above 6000 rpm must add dq cross-decoupling feed-forward (ω·Lq·iq, ω·Ld·id + ω·ψf).',
  ],
  steps: [
    {
      id: 'see-axes',
      title: '看坐标',
      goal: '建立"αβ 是焊死的地面、dq 是焊在转子上的旋转转盘"几何直觉',
      goalEn: 'Build the geometric intuition that "αβ is welded to the ground, dq is a spinning turntable welded to the rotor".',
      action: '观察主图：蓝色箭头 = αβ 电流矢量（默认 Iα=5、Iβ=0）；中间转子贴 N/S 永磁体；绿色 d 轴沿 N 极；红色 q 轴领先 d 轴 90°（电角度）。',
      observe: '右侧 VectorPlane 显示同一份数据另一种画法：αβ 网格不动，d/q 轴在网格上随 θ 旋转。',
      observeEn: 'The VectorPlane on the right shows the same data another way: the αβ grid is stationary while the d/q axes rotate over the grid with θ.',
      whyMatters: 'αβ = 焊在定子上的静止坐标，跟编码器、ADC、PWM 三相端子有固定几何对应。dq = 焊在转子上的旋转坐标，跟随转子永磁体走。FOC 所有 PI 工作发生在 dq 域。家用空调压缩机 6 极对，机械转 1000 rpm = 电角度 100 Hz；电流环 ISR 里 Park 每 50-100 μs 调一次，是 STM32 上调用频率最高的纯函数之一。',
      whyMattersEn: 'αβ is a stationary frame welded to the stator with a fixed geometric mapping to encoder, ADC, and PWM terminals. dq is a rotating frame welded to the rotor, tracking the magnets. All FOC PI work happens in dq. On a 6 pole-pair HVAC compressor, 1000 rpm mechanical = 100 Hz electrical; Park runs every 50–100 μs in the current-loop ISR, one of the most frequently called pure functions on an STM32.',
    },
    {
      id: 'theta-zero',
      title: 'θ=0 投影',
      goal: '在 d 轴和 α 轴对齐时验证 Park 公式（单元测试零点）',
      goalEn: 'Verify the Park formula at θ = 0 with the d axis aligned to the α axis (unit-test zero point).',
      action: '把"电角度 θ"滑块拖到 0°，保持 Iα=5、Iβ=0。',
      observe: '主图绿色 Id 线段 ≈ 5A，红色 Iq 线段 ≈ 0A；右下数值卡片 Id≈5、Iq≈0。',
      observeEn: 'The green Id segment reads ≈ 5 A and the red Iq segment ≈ 0 A; the value card shows Id ≈ 5, Iq ≈ 0.',
      whyMatters: 'θ=0 时 cos=1、sin=0，Park 矩阵退化为单位阵，Id=Iα、Iq=Iβ。这是 STM32 上验证你的 sin/cos 写对没有的最简单零点检查——单元测试固化为 ASSERT_NEAR(park(5, 0, 0).id, 5, 1e-4)。生产工程里 sin/cos 通常不调 math.h（μs 级别太慢），而是 256/512/1024 点表查 + 线性插值；表生成时 θ=0 那一格直接写 (1, 0) 跳过插值，避免 0.999/0.001 这种典型查表精度问题。',
      whyMattersEn: 'At θ = 0, cos = 1 and sin = 0, so Park reduces to the identity: Id = Iα, Iq = Iβ. This is the simplest zero-point check that your STM32 sin/cos implementation is correct — pin it as `ASSERT_NEAR(park(5, 0, 0).id, 5, 1e-4)` in unit tests. In production, sin/cos is not called from math.h (μs-scale, too slow); a 256/512/1024-point table with linear interpolation is used, and the θ = 0 entry is hard-coded as (1, 0) to skip interpolation and avoid typical lookup-precision issues like 0.999 / 0.001.',
      presetId: 'park-dc',
      quiz: {
        q: 'θ=0、Iα=5、Iβ=0。按 Park 公式 Id = Iα·cosθ + Iβ·sinθ，Id 应等于？',
        options: ['0（θ 是 0 没有投影）', '5（cos(0)=1、sin(0)=0，Id=Iα）', '5·cos(45°) ≈ 3.5（45° 投影）', '需要先知道转速 ω'],
        correct: 1,
        hint: 'cos(0)=1、sin(0)=0，Id=5·1+0·0=5。Park 在 θ=0 时不做任何事。选项 A 把"投影 0°"误解成"投影量 0"；选项 C 误以为 sin/cos 在不同步时算同一角度；选项 D 把 Park（纯几何变换）与速度环混淆了——Park 不需要 ω，只需要 θ。',
        qEn: 'With θ = 0, Iα = 5, Iβ = 0, what is Id from Park (Id = Iα·cosθ + Iβ·sinθ)?',
        optionsEn: [
          '0 (θ = 0 means no projection)',
          '5 (cos(0) = 1, sin(0) = 0, so Id = Iα)',
          '5·cos(45°) ≈ 3.5 (a 45° projection)',
          'You first need to know the speed ω',
        ],
        hintEn: 'cos(0) = 1, sin(0) = 0 → Id = 5·1 + 0·0 = 5. At θ = 0, Park is the identity. Option A confuses "0° projection" with "zero projection"; option C treats sin and cos as evaluated at different angles; option D confuses Park (a pure geometric transform) with the speed loop — Park needs only θ, not ω.',
      },
    },
    {
      id: 'theta-90',
      title: 'θ=90° 投影',
      goal: '看到"同一个 αβ 矢量、不同 θ 投出完全不同的 Id/Iq"',
      goalEn: 'See that the same αβ vector projects to completely different Id/Iq under different θ.',
      action: '保持 Iα=5、Iβ=0 不动，把 θ 从 0° 慢慢拖到 90°。',
      observe: 'Id 从 5A 一路掉到 0A；Iq 从 0A 一路涨到 −5A（θ=90° 时 −Iα·sin(90°)=−5）。√(Id²+Iq²) 始终 ≈ 5。',
      observeEn: 'Id falls from 5 A to 0; Iq rises from 0 to −5 A (at θ = 90°, −Iα·sin(90°) = −5). √(Id² + Iq²) stays ≈ 5 throughout.',
      whyMatters: '"同一束 αβ 在不同 θ 下投影不同"——这是 FOC 必须实时拿到准确 θ 的几何根。Park 不改电流"大小"，只改"用哪两根轴表达"。STM32 实现里 θ 通常用 q31 表示一整圈（0~2³¹ = 0~2π），整数溢出 = 自动归一，省掉 fmodf。但要注意：q31 累加 ω·Ts 时一旦 ω 或 Ts 用错单位（如 mech vs elec、Hz vs rad/s），整圈周期就完全错——这种 bug 一上电不转或反转，逐级 printf 是查不到的，要用示波器看实际 θ 增长速率。',
      whyMattersEn: '"The same αβ vector projects differently at different θ" — the geometric reason FOC must obtain accurate θ in real time. Park does not change the current magnitude, only which two axes express it. In STM32, θ is usually stored as q31 covering one revolution (0..2³¹ = 0..2π), so overflow auto-wraps and fmodf is unnecessary. But watch out: when integrating q31 += ω·Ts, a unit mistake (mechanical vs electrical, Hz vs rad/s) makes the revolution period completely wrong — such bugs cause "won\'t spin / runs backward" at first boot and printf debugging is useless; use a scope to measure the real θ growth rate.',
    },
    {
      id: 'rotate-theta',
      title: 'θ 旋转一圈',
      goal: '看到旋转坐标下 αβ 的 AC 量变成 DC 量（动态版）',
      goalEn: 'Watch αβ AC quantities become DC in the rotating frame (dynamic version).',
      action: '维持 Iα=5、Iβ=0，把 θ 从 0° 缓慢扫到 360°，观察 Id/Iq 数字变化轨迹。',
      observe: 'Id 沿 +cos 曲线起伏：5 → 0 → −5 → 0 → 5；Iq 沿 −sin 曲线：0 → −5 → 0 → 5 → 0。',
      observeEn: 'Id traces a +cos curve: 5 → 0 → −5 → 0 → 5; Iq traces −sin: 0 → −5 → 0 → 5 → 0.',
      whyMatters: '反过来想：电机正在转，αβ 是旋转箭头，控制器算的 θ 让它"跟住转子"——那么 dq 坐标里看到的就是不动的两根棍子（DC 量）。PI 控直流，零稳态误差由此而来。这是 FOC 相比标量 V/f 控制带宽高一个数量级的根本原因。',
      whyMattersEn: 'Inverted: the motor is spinning, αβ is a rotating arrow, the controller\'s θ tracks the rotor — so in dq you see two stationary sticks (DC). PI regulates DC, hence zero steady-state error. This is the fundamental reason FOC has an order-of-magnitude higher bandwidth than scalar V/f control.',
      quiz: {
        q: '电机恒电频率运行，αβ 是 50 Hz 旋转正弦量。若控制器的 θ 恰好跟转子电角度同步（θ_PLL = θ_real），Id/Iq 在示波器上的形状是？',
        options: [
          '50 Hz 正弦（θ 没消掉 AC）',
          '直流（同步旋转 = αβ 在 dq 视角里"不动"）',
          '100 Hz 正弦（θ 把基波倍频）',
          '直流叠加 100 Hz 纹波（θ 抖动残留）',
        ],
        correct: 1,
        hint: '同步旋转 = αβ 在 dq 视角里"不动了"。选项 D 是"θ 估算带噪声"的真实情况，但题目假设 θ_PLL 恰好同步；选项 C 是常见的过零谐波担忧但与 Park 几何无关。',
        qEn: 'A motor runs at constant electrical frequency; αβ is a 50 Hz rotating sinusoid. If the controller\'s θ is perfectly synced to the rotor (θ_PLL = θ_real), what shape do Id/Iq take on a scope?',
        optionsEn: [
          '50 Hz sinusoid (θ has not removed the AC)',
          'DC (synchronous rotation = αβ "stands still" in the dq view)',
          '100 Hz sinusoid (θ doubles the fundamental)',
          'DC with 100 Hz ripple (residual from θ jitter)',
        ],
        hintEn: 'Synchronous rotation = αβ "stands still" in dq. Option D is the realistic case with θ estimation noise, but the question assumes perfect sync; option C is a common zero-crossing-harmonic worry that is unrelated to Park geometry.',
      },
    },
    {
      id: 'pure-iq-q15',
      title: '纯转矩 + Q15 实现',
      goal: '理解"为什么 FOC 默认 Id=0"，并体验 Cortex-M3 Q15 定点 Park 落地',
      goalEn: 'Understand why FOC defaults to Id = 0 and walk through a Cortex-M3 Q15 fixed-point Park.',
      action: '拖 Iα、Iβ 让 αβ 矢量与 q 轴对齐（θ=0 时 Iα=0、Iβ=5）。再阅读下方 STM32 代码片段。',
      observe: 'Id≈0、Iq≈5。Iq 一安每安换成转矩，Id 只产生铜损不产生转矩（表贴式 PMSM 场景）。',
      observeEn: 'Id ≈ 0, Iq ≈ 5. Every amp of Iq produces torque; Id only produces copper loss with no torque (SPM case).',
      whyMatters: 'd 轴沿永磁体磁链方向，加 Id 只是给磁链"加塞"，对 SPM 不产生转矩还白白耗 I²Rs。Iq 与磁链正交，每安培都换成 Te=1.5·p·ψf·Iq。Cortex-M3 Q15 实现参考（电流单位为 q15，θ 用 0~32767 表示 0~2π，sin_tab 是 1024 点 q15 查表）：' +
        ' int16_t sin_q15 = sin_tab[theta_q15 >> 5];' +
        ' int16_t cos_q15 = sin_tab[((theta_q15 >> 5) + 256) & 0x3FF];' +
        ' /* id = (i_alpha*cos + i_beta*sin) >> 15 — 注意先 int32 中间值防溢出 */' +
        ' int32_t id32 = (int32_t)i_alpha*cos_q15 + (int32_t)i_beta*sin_q15;' +
        ' int32_t iq32 = (int32_t)-i_alpha*sin_q15 + (int32_t)i_beta*cos_q15;' +
        ' int16_t id_q15 = (int16_t)(id32 >> 15);' +
        ' int16_t iq_q15 = (int16_t)(iq32 >> 15); — 这就是国内中低端压缩机 MCU 的标准模板，10 个时钟周期完成一次 Park。',
      whyMattersEn: 'The d axis points along the permanent-magnet flux; adding Id only "stuffs more flux", which on SPM yields no torque and only wastes I²Rs. Iq is orthogonal to the flux and every amp converts to Te = 1.5·p·ψf·Iq. Cortex-M3 Q15 reference (currents in q15; θ in 0..32767 representing 0..2π; sin_tab is a 1024-point q15 table): read sin_q15 = sin_tab[theta_q15 >> 5] and cos_q15 = sin_tab[((theta_q15 >> 5) + 256) & 0x3FF]; compute id32 = (int32_t)i_alpha*cos_q15 + (int32_t)i_beta*sin_q15 and iq32 = (int32_t)(-i_alpha)*sin_q15 + (int32_t)i_beta*cos_q15 (promote to int32 first to avoid overflow); finally id_q15 = (int16_t)(id32 >> 15) and iq_q15 = (int16_t)(iq32 >> 15). This is the standard template on mid- and low-end domestic compressor MCUs — one Park in about 10 cycles.',
    },
    {
      id: 'theta-error',
      title: 'Δθ 串扰',
      goal: '看到"角度误差 → dq 串扰"这条最常见的现场坑',
      goalEn: 'See the most common field pitfall: angle error → dq crosstalk.',
      action: '设 Iα=0、Iβ=5（理想纯 Iq）；把 θ 从 0° 拖到 15°。',
      observe: 'Id 不再是 0，浮起约 −5·sin(15°) ≈ −1.29A；Iq 缩到 5·cos(15°) ≈ 4.83A。',
      observeEn: 'Id is no longer 0 but ≈ −5·sin(15°) ≈ −1.29 A; Iq shrinks to 5·cos(15°) ≈ 4.83 A.',
      whyMatters: '编码器零位没对齐 / 无感观测器有偏差，θ 就有恒定误差 Δθ。Park 把"本该全是 Iq"按 sin(Δθ) 漏到 Id：1° 漏 1.7%，5° 漏 8.7%，15° 漏 26%——这是 STM32 联调中"电流大转矩小"的几何根。同时还有"Id 控不到 0"的次生现象：你给 Id*=0 但实测 Id≈−1.3A，电流环 PI 拼命输出负 Vd 抵消，结果 Vd/Vq 命令偏离最优点，效率掉 5-10%。生产排障口诀：iq*=正、id*=0、实测 id 非零 → 先查 Park 的 θ，不是 PI。',
      whyMattersEn: 'If the encoder zero is misaligned or the sensorless observer is biased, θ carries a constant error Δθ. Park leaks "what should be pure Iq" into Id by sin(Δθ): 1.7% at 1°, 8.7% at 5°, 26% at 15° — the geometric root of "high current, low torque" in STM32 bring-up. A secondary symptom is "Id will not be regulated to 0": you set Id* = 0 but measure Id ≈ −1.3 A, the current PI fights with negative Vd to compensate, the Vd/Vq command shifts off the optimum, and efficiency drops 5–10%. Production troubleshooting rule: iq* > 0, id* = 0, measured id ≠ 0 → check Park\'s θ first, not the PI.',
      quiz: {
        q: '现场调试给 Iq*=5A、Id*=0，但 Iq 实测 4.85A、Id 实测 −1.3A。最优先该改什么？',
        options: [
          '加大电流采样滤波器抑制偏置',
          '减小电流环 Kp 让 Id 慢慢被压回 0',
          '重做编码器零位对齐：sin(Δθ) ≈ 1.3/5 = 0.26 → Δθ ≈ 15°',
          '增加母线电压让 PI 有更多余量',
        ],
        correct: 2,
        hint: 'sin(15°)·5 ≈ 1.29、cos(15°)·5 ≈ 4.83，几何上正好是 Park 角度误差。Park 是纯几何变换不带动态——选 A/B/D 都是把"几何错位"当成"动态问题"处置，越改越乱。修法：上电先做 d 轴对齐（Id 直流 + Iq=0 锁轴 → 把当前 encoder 计数当 θe=0）；或加增量编码器 Z 信号每圈校一次。',
        qEn: 'In the field you command Iq* = 5 A, Id* = 0 but measure Iq = 4.85 A, Id = −1.3 A. What is the top-priority fix?',
        optionsEn: [
          'Add a heavier current-sample filter to suppress the offset',
          'Lower the current-loop Kp so Id is slowly pushed back to 0',
          'Re-do the encoder zero alignment: sin(Δθ) ≈ 1.3/5 = 0.26 → Δθ ≈ 15°',
          'Raise the DC link to give the PI more headroom',
        ],
        hintEn: 'sin(15°)·5 ≈ 1.29, cos(15°)·5 ≈ 4.83 — exactly the geometry of a Park angle error. Park is a purely geometric transform with no dynamics, so options A/B/D treat a geometric misalignment as a dynamic problem and make things worse. The fix: at boot run a d-axis alignment (DC Id with Iq = 0 to lock the axis → treat the current encoder count as θe = 0); or add an incremental encoder Z pulse to recalibrate once per revolution.',
      },
    },
    {
      id: 'encoder-z-sync',
      title: '编码器 Z 信号校准',
      goal: '掌握"每圈一次硬件 Z 信号"对 Park 角度长期稳定性的作用',
      goalEn: 'Master the role of a once-per-revolution hardware Z pulse for long-term Park angle stability.',
      action: '想象一台 2500 PPR 的增量编码器接到 STM32 TIM2 32 位计数器；A/B 正交 4 倍频后单圈 10000 计数。Z 信号每圈一次脉冲，接 TIM2_CH3 + 输入捕获中断。',
      observe: '理想情况下电机转 N 圈后计数器读数应为 N·10000；若中间漏了一次 A 边沿，每漏 1 个计数 θe 就永久偏 0.036°·polePairs。漏 4 个就累计 0.15°·polePairs，对 6 极对压缩机 = 0.9° 电角度漂移。',
      observeEn: 'Ideally after N revolutions the counter reads N·10000; missing a single A edge permanently shifts θe by 0.036° × polePairs. Four missed counts compound to 0.15° × polePairs ≈ 0.9° electrical drift on a 6 pole-pair compressor.',
      whyMatters: 'A/B 计数会因 EMI / 软件中断抢占 / 编码器线接触不良漏脉冲，长时间运行后 θm 漂移；θe = θm·polePairs 把漂移放大 polePairs 倍。Z 信号是硬件复位锚点：HAL_TIM_IC_CaptureCallback 里把 TIM2->CNT 直接写成"已知 Z 位置对应的计数值"（比如 0 或 5000），把累积漂移一次性清零。压缩机这种 24/7 运行场景，没有 Z 校准的 FOC 跑 8 小时后效率会肉眼可见下降 1-2%。无 Z 编码器（如磁编码器）必须配合 BEMF 观测器做长期校准。',
      whyMattersEn: 'A/B counts can be lost from EMI, ISR preemption, or poor contact; over long runs θm drifts and θe = θm·polePairs amplifies the drift by polePairs. The Z pulse is a hardware reset anchor: in HAL_TIM_IC_CaptureCallback, write TIM2->CNT to the known Z position (e.g. 0 or 5000) to clear the accumulated drift in one go. For 24/7 compressor runs, an FOC without Z calibration loses 1–2% efficiency visibly after 8 hours. Encoder types without a Z pulse (e.g. magnetic) must be paired with a BEMF observer for long-term calibration.',
      quiz: {
        q: '2500 PPR 增量编码器 + 6 极对 PMSM，A/B 信号在 EMI 干扰下平均每分钟漏 10 个计数边沿。运行 1 小时后 θe 累积偏差大约？',
        options: [
          '0°（4 倍频后冗余可以容错）',
          '约 0.36°（仅机械角度漂）',
          '约 2.16°（机械漂 × 极对数）',
          '约 21.6°（计数器溢出）',
        ],
        correct: 2,
        hint: '60 分钟 × 10 = 600 个漏脉冲；每个对应 360°/10000 = 0.036° 机械；600·0.036° = 21.6° 机械；× 6 极对 = 129° 电角度——已经完全不能控了。但 Z 每圈复位一次只会累积"当圈内"的漏数，所以实际偏差 ≈ 10 漏/分 ÷ 转速 × 0.036° × 6 ≈ 2.16° 电角度（按 3000 rpm 估算）。选项 D 是不加 Z 信号 1 小时的真实灾难。',
        qEn: 'A 2500 PPR incremental encoder + 6 pole-pair PMSM loses 10 edges per minute under EMI on average. After 1 hour, what is the accumulated θe drift?',
        optionsEn: [
          '0° (×4 decoding tolerates errors)',
          'About 0.36° (mechanical drift only)',
          'About 2.16° (mechanical drift × pole pairs)',
          'About 21.6° (counter overflow)',
        ],
        hintEn: '60 min × 10 = 600 missed pulses; each = 360°/10000 = 0.036° mechanical; 600·0.036° = 21.6° mechanical; × 6 pole pairs = 129° electrical — completely uncontrollable. But with Z resetting once per revolution you only accumulate within-revolution losses, so actual drift ≈ 10/min ÷ rpm × 0.036° × 6 ≈ 2.16° electrical (assuming 3000 rpm). Option D is the real disaster after one hour without a Z pulse.',
      },
    },
    {
      id: 'decoupling-feedforward',
      title: '高速 dq 解耦前馈',
      goal: '理解为什么 6000 rpm+ 必须给 Park 后的 Vd/Vq 加交叉项前馈',
      goalEn: 'Understand why above 6000 rpm a cross-term feed-forward must be added to Vd/Vq.',
      action: '回顾 PMSM dq 电压方程：Vd = Rs·Id + Ld·dId/dt − ωe·Lq·Iq；Vq = Rs·Iq + Lq·dIq/dt + ωe·(Ld·Id + ψf)。其中 ωe·Lq·Iq 和 ωe·Ld·Id 是"交叉项"，ωe·ψf 是 BEMF。',
      observe: '低速（ωe 小）时交叉项 < 1V，可忽略；高速（ωe = 2π·100Hz = 628 rad/s）时 ωe·Lq·Iq = 628·0.001·10 = 6.28V，已占母线 10%；6000 rpm 6 极对时 ωe = 3770 rad/s，交叉项 38V 占满量程。',
      observeEn: 'At low speed (small ωe) the cross terms are < 1 V, negligible; at high speed (ωe = 2π·100 Hz = 628 rad/s) ωe·Lq·Iq = 628·0.001·10 = 6.28 V, already 10% of the bus; at 6000 rpm × 6 pole pairs, ωe = 3770 rad/s, the cross term reaches 38 V, eating most of the headroom.',
      whyMatters: '不加解耦的纯 PI 在高速下会"拼命对抗交叉扰动"——PI 输出几乎全花在抵消 ωe·L·I，留给动态响应的余量很少，表现为高速段电流环带宽崩塌、Iq 命令跟踪误差变大、转矩纹波 + 噪声。前馈实现：vd_cmd = pi_d_out − omega_e * Lq * iq；vq_cmd = pi_q_out + omega_e * (Ld * id + psi_f);  其中 omega_e 用速度环估算值，Ld/Lq/ψf 是离线辨识参数。STM32 上前馈是 ISR 内 4 次乘加（~1 μs），但能让电流环带宽在高速段不下降 50% 以上。压缩机 4000 rpm 以上必加，否则爬升时听得到"嗡"的电流噪声。',
      whyMattersEn: 'A bare PI without decoupling spends almost all its output fighting ωe·L·I at high speed, leaving little headroom for dynamic response — visible as collapsing current-loop bandwidth, larger Iq tracking error, torque ripple, and noise. Feed-forward implementation: vd_cmd = pi_d_out − omega_e · Lq · iq; vq_cmd = pi_q_out + omega_e · (Ld · id + psi_f); use the speed-loop estimate for omega_e and offline-identified values for Ld/Lq/ψf. On STM32 the feed-forward adds four multiply-adds in the ISR (~1 μs) and prevents the current-loop bandwidth from collapsing by 50%+ at high speed. Mandatory for compressors above 4000 rpm; without it you can hear the current "hum" during acceleration.',
      quiz: {
        q: 'PMSM 极对数 6、Lq = 1.5 mH、Iq = 8A、转速 5000 rpm，q 轴交叉耦合电压 ωe·Lq·Iq 大约？',
        options: ['0.6V（基本可忽略）', '6V（10% 母线）', '38V（占满 1/3 母线）', '380V（远超母线）'],
        correct: 2,
        hint: 'ωe = 2π·(5000/60)·6 ≈ 3142 rad/s；ωe·Lq·Iq = 3142·0.0015·8 ≈ 38V。310V 母线下已占 12% — 不加前馈，PI 输出端干这一项就要 38V 余量，剩下控动态的余量大大压缩。这就是"低速好好的高速一加载就抖"的常见根因。',
        qEn: 'PMSM with 6 pole pairs, Lq = 1.5 mH, Iq = 8 A, 5000 rpm — what is the q-axis cross-coupling voltage ωe·Lq·Iq?',
        optionsEn: [
          '0.6 V (essentially negligible)',
          '6 V (~10% of the bus)',
          '38 V (about 1/3 of the bus)',
          '380 V (far above the bus)',
        ],
        hintEn: 'ωe = 2π·(5000/60)·6 ≈ 3142 rad/s; ωe·Lq·Iq = 3142·0.0015·8 ≈ 38 V. On a 310 V bus that is 12% — without feed-forward, the PI output must dedicate 38 V to this term, leaving little for dynamics. This is the typical root cause of "fine at low speed, jittery as soon as load comes on at high speed".',
      },
    },
    {
      id: 'inverse-park-pipeline',
      title: '反 Park 与全流水线',
      goal: '把 Park / 反 Park 接回完整 FOC ISR',
      goalEn: 'Wire Park / inverse Park back into the full FOC ISR.',
      action: '回想 PWM 周期内 FOC ISR 完整流水线：ADC 触发 → 读 Ia/Ib 重构 Ic → Clarke → Park → 电流 PI → 解耦前馈 → 反 Park → SVPWM → 写 CCR。',
      observe: 'Park 在前端把"测的 αβ 电流"变 dq 给 PI；反 Park 用同一个 θ（矩阵转置 = 旋转 −θ）把"PI 算的 Vdq"变回 αβ 给 SVPWM。一个 θ 错了，两次都错。',
      observeEn: 'Park converts measured αβ currents into dq for the PI; inverse Park uses the same θ (matrix transpose = rotate by −θ) to convert the PI\'s Vdq back to αβ for SVPWM. One wrong θ corrupts both.',
      whyMatters: 'Park / 反 Park 是 FOC 流水线里唯一与转子角度强耦合的两段——θ 抖动会同时在采样侧污染 Id/Iq、在输出侧污染 Vα/Vβ。"角度质量"决定 FOC 上限：编码器分辨率、Z 信号校准、PLL 噪声、Park 计算精度（q15 vs float）一层层叠加。压缩机 PWM 16 kHz 下，Park 必须 < 5 μs 完成（含 sin/cos 查表 + 4 次乘加 + 2 次右移归一），否则 ISR 预算超支 → 速度环挤不进 1 kHz 任务 → 整个调度崩。',
      whyMattersEn: 'Park / inverse Park are the only two stages in the FOC pipeline tightly coupled to the rotor angle — θ jitter pollutes Id/Iq on the sampling side and Vα/Vβ on the output side simultaneously. "Angle quality" sets the upper bound on FOC: encoder resolution, Z calibration, PLL noise, and Park precision (q15 vs float) all stack up. With 16 kHz PWM on a compressor, Park must complete in < 5 μs (including sin/cos lookup + 4 multiply-adds + 2 right shifts) — otherwise the ISR budget blows, the 1 kHz speed-loop task does not fit, and the whole schedule collapses.',
    },
  ],
  pitfalls: [
    {
      id: 'mechanical-theta',
      label: '试错：用机械角度代替电角度（漏乘 polePairs）',
      labelEn: 'Mis-step: use mechanical angle instead of electrical (forgot ×polePairs)',
      symptom: 'Park 矩阵旋转速率慢 polePairs 倍，dq 量仍以电频率波动；Iq 阶跃响应 = 同频纹波 ± 直流',
      symptomEn: 'The Park matrix rotates polePairs× too slowly, dq quantities still oscillate at electrical frequency; Iq step response = same-frequency ripple ± DC.',
      why: 'θe 必须 = θm × polePairs。压缩机 4-6 极对时漏乘几乎一定上电不转或反转。常见踩坑情境：① 直接用 encoder 计数器值（机械单位）当 θe；② 把"4 极电机"误填成 4 而不是 2；③ 双编码器系统（一个机械、一个电机）变量名搞混。修复：在 update_theta_e() 里强制 theta_e_q15 = (uint16_t)((int32_t)theta_m_q15 * POLE_PAIRS) — 用宏 POLE_PAIRS 而非散落的字面量。',
      whyEn: 'θe must equal θm × polePairs. On a 4–6 pole-pair compressor, forgetting this multiplication almost always causes "no spin / reverse spin" at first boot. Common trip-ups: (1) using the raw encoder counter (mechanical units) as θe; (2) entering "4-pole motor" as 4 instead of 2; (3) variable-name mix-up on dual-encoder systems (one mechanical, one electrical). Fix: in `update_theta_e()` enforce `theta_e_q15 = (uint16_t)((int32_t)theta_m_q15 * POLE_PAIRS)` and use the `POLE_PAIRS` macro everywhere — no stray literals.',
    },
    {
      id: 'wrong-direction',
      label: '试错：θ 方向取反（encoder 计数方向 vs 电机机械正转不匹配）',
      labelEn: 'Mis-step: θ direction inverted (encoder count direction does not match motor forward rotation)',
      symptom: 'Iq*=+5A，电机反方向转或卡死抖动；电流幅值正常但转矩方向反',
      symptomEn: 'Iq* = +5 A but the motor spins backward or stalls and shudders; current magnitude is normal but torque direction is reversed.',
      why: '编码器 A/B 信号接线方向 vs 电机机械正转定义如果不一致，θ 增长方向就反了。Park 把"按你以为的 q 轴方向"投到了反向 q 轴 → PI 给出反向 Vq → 反向 Iq → 反向转矩 → 闭环发散。第一次上电必须低压（1/3 母线）+ 开环 V/f 慢拖（10 rpm）验证 θ 增长方向；不匹配时 swap encoder A/B 接线或软件取反 TIM_EncoderMode_TI1。这是新机型量产前必做检测。',
      whyEn: 'If the encoder A/B wiring direction does not match the motor\'s defined forward rotation, θ grows in the wrong direction. Park projects onto the "q axis you think exists" but is actually the reversed q axis → the PI outputs reversed Vq → reversed Iq → reversed torque → the closed loop diverges. At first boot, run low-voltage (1/3 of bus) open-loop V/f at 10 rpm to verify θ growth direction; if it mismatches, swap encoder A/B wires or invert TIM_EncoderMode_TI1 in software. Mandatory check before mass-producing a new model.',
    },
    {
      id: 'q15-overflow',
      label: '试错：Q15 Park 直接 (int16) * (int16) 不升 int32',
      labelEn: 'Mis-step: Q15 Park multiplies (int16) × (int16) without promoting to int32',
      symptom: '电流幅值超过 0.7·Imax 时 Id/Iq 出现"折返"或"夹断"，波形顶部削平',
      symptomEn: 'When current amplitude exceeds 0.7·Imax, Id/Iq exhibit "fold-back" or "clipping", with waveform tops flattened.',
      why: 'Q15 范围 [-1, 1) 对应 int16 [-32768, 32767]。两个 Q15 相乘等价于 (a/2¹⁵)·(b/2¹⁵) = ab/2³⁰，但中间值 ab 已是 int32（最大 ~2³⁰）。如果代码写成 int16 result = (int16)(i_alpha * cos_q15)，乘法在 16 位寄存器里就溢出截断了，结果完全错。修复：所有 q15 乘法中间必须升 int32，最后 >> 15 再降回 int16；ARM Cortex-M 的 __SMMLA / __SMMUL 内联汇编是为这件事专门设计的，比 C 写法快 2 倍。',
      whyEn: 'Q15 [-1, 1) maps to int16 [-32768, 32767]. Two q15 multiplies = (a/2¹⁵)·(b/2¹⁵) = ab/2³⁰, but the intermediate ab is int32 (up to ~2³⁰). If you write `int16 result = (int16)(i_alpha * cos_q15)` the multiply overflows and truncates inside a 16-bit register — result is wrong. Fix: every q15 multiply must use int32 for the intermediate, then >> 15 back to int16; ARM Cortex-M\'s __SMMLA / __SMMUL inline assembly is purpose-built for this and is 2× faster than the C version.',
    },
    {
      id: 'theta-discontinuous',
      label: '试错：θ 用 float 累加不做 2π 归一化',
      labelEn: 'Mis-step: accumulate θ in float without 2π normalization',
      symptom: 'θ 累加到 |θ| > 1e4 rad 时 sinf/cosf 精度断崖式下降；电流环莫名抖动且无法复现',
      symptomEn: 'When θ accumulates to |θ| > 1e4 rad, sinf/cosf precision falls off a cliff; the current loop jitters mysteriously and the issue is not reproducible.',
      why: 'float 单精度尾数 23 位，|θ| > 8192 时相邻浮点数间距 > 0.001，sin/cos 误差到 0.1%；|θ| > 1e6 时几乎无精度。每次进 Park 前必须把 θ 模 2π（或用 q31 自然溢出）。STM32 上 fmodf 比 while(theta>2π) theta-=2π 更稳（后者在 |theta|>>2π 时会卡很久）。最佳实践：θ 用 q31 整数表示（0..2³¹ 映射 0..2π），溢出 = 自动归一，省 fmodf，且 sin/cos 查表索引直接 theta_q31 >> (31-LOG2_TABLE_SIZE) 一行搞定。',
      whyEn: 'Single-precision float has 23 bits of mantissa; at |θ| > 8192 adjacent floats are spaced > 0.001 apart and sin/cos error reaches 0.1%; at |θ| > 1e6 there is essentially no precision left. Always mod 2π before Park (or use q31 with natural overflow). On STM32, fmodf is more stable than `while (theta > 2π) theta -= 2π` (the latter spins for ages when |theta| >> 2π). Best practice: store θ as q31 (0..2³¹ maps 0..2π), overflow = auto-wrap, no fmodf needed, and the sin/cos table index reduces to `theta_q31 >> (31 - LOG2_TABLE_SIZE)` in one line.',
    },
  ],
  nextModuleHook: 'Park 把 αβ 变成了"PI 能控的直流量"，并且你已经知道 Q15 实现、Z 信号校准、解耦前馈三道工业坎。下一模块（05 PID）就拿这两根直流量来真正闭环——Kp = ω_bw·L 起步、抗积分饱和怎么写、采样周期 Ts 改了为什么 Ki 跟着改。',
  nextModuleHookEn: 'Park converts αβ into "DC quantities the PI can regulate", and you now know three industrial hurdles: Q15 implementation, Z calibration, and decoupling feed-forward. Module 05 (PID) closes the loop on these two DC quantities — Kp = ω_bw·L as a starting point, how to code anti-windup, and why changing the sample period Ts forces Ki to change with it.',
};
